### PR TITLE
Tweak performance of Specs benchmarks

### PR DESCRIPTION
**Pull request by torkleyy**
* Used `VecStorage`, which is more efficient here
* More parallel execution in the parallel benchmark
* `RunNow` for the single system
* Update to Specs 0.10

### CODE REVIEW

**Comment by lschmierer** [comment]
Looks fine

**Comment by torkleyy** [comment]
Thanks for merging! It seems that no benchmark has been triggered?

**Comment by lschmierer** [comment]
oh, yes
I accidentally merged into the master branch while I should merge into the bench branch.
Travis then pushes the results onto master

This workflow is a little confusing and can probably be optimized somehow

**Comment by torkleyy** [comment]
Oh I didn't know, otherwise I would have created the PR against `bench`.

**Comment by lschmierer** [comment]
It is possible to set the default branch on github. The default branch is the primarily shown branch and also the branch that pull requests are created against.
The problem is, that it is not possible to select two different branches for that.
So this will always be a little inconvenient.

**Comment by torkleyy** [comment]
You could push the benchmark results to `gh-pages` and link to that maybe.

**Pull request merged**
